### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by xynree** [xynree/rating-room-r#2]
Minimum viable product:

- [x] User can add items with a name, rating, desciption, and categories #10 #19 
- [x] User can edit ratings on an item #10 #19 
- [x] User can add images to an item #10 #19 
- [ ] User can filter items by rating and categories #46 
- [ ] User can sort by date added, name and ratings #47
- [ ] User can add and delete categories #43 #45 
- [ ] User can navigate between items from main collection or from individual item pages #41 
- [ ] Styling matches [Figma](https://www.figma.com/file/Cee0DHL4rcs134B8G74ytr/Rating-Room-r?node-id=0%3A1&t=5Q3u72kDLgJDCkfE-1) comps #44 
- [ ] Change icon #49
